# Generated by Django 4.0.2 on 2022-04-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluationapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescription',
            name='experience_in_years',
            field=models.FloatField(),
        ),
    ]
